### ISSUE TITLE
Uniformizar idioma no sistema

### ISSUE THREAD

**Issue by trandreluis** [Edwin160508/social-books-api#3]
Modificar o idioma da classe DetalheErro para português, o que for possível.

**Comment by Edwin160508** [comment]
Renomeado atributos e métodos da classe afim de Uniformizar idioma no sistema.
Agradeço o seu feedback.

**Comment by trandreluis** [comment]
Alterar menssagemDesenvolvida para menssagemDesenvolvedor;
Alterar tempo para dataHora.
